CREATE TABLE categories(
    category_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    category_name VARCHAR2(100) NOT NULL,
    description VARCHAR2(200),
    CONSTRAINT pk_categories PRIMARY KEY(category_id),
    CONSTRAINT uq_category_name UNIQUE(category_name)
);



CREATE TABLE suppliers(
    supplier_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    supplier_name VARCHAR2(100) NOT NULL,
    company_name VARCHAR2(100),
    phone VARCHAR2(20),
    email VARCHAR2(100),
    address VARCHAR2(200),
    status VARCHAR2(20) DEFAULT ('ACTIVE'),
    CONSTRAINT pk_suppliers PRIMARY KEY(supplier_id),
    CONSTRAINT uq_supplier_email UNIQUE(email),
    CONSTRAINT uq_supplier_status CHECK(status IN ('ACTIVE', 'INACTIVE', 'BLOCKED'))
);



CREATE TABLE customers(
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    customer_name VARCHAR2(100) NOT NULL,
    phone VARCHAR2(20),
    address VARCHAR2(200),
    CONSTRAINT pk_customers PRIMARY KEY(customer_id)
);


CREATE TABLE users_system(
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR2(100) NOT NULL,
    full_name VARCHAR2(100) NOT NULL,
    password VARCHAR2(100) NOT NULL,
    role VARCHAR2(30) DEFAULT 'CASHIER',
    status VARCHAR2(20) DEFAULT 'ACTIVE',
    created_at DATE DEFAULT SYSDATE,
    CONSTRAINT pk_users PRIMARY KEY(user_id),
    CONSTRAINT uq_username UNIQUE(username),
    CONSTRAINT chk_user_status CHECK(status IN ('ACTIVE','INACTIVE'))
);



CREATE TABLE products(
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    product_name VARCHAR2(100) NOT NULL,
    category_id NUMBER NOT NULL,
    barcode VARCHAR2(100) NOT NULL,
    unit VARCHAR2(100) NOT NULL,
    minimum_profit_percent NUMBER(5,2) DEFAULT 20,
    reorder_level NUMBER DEFAULT 10,
    status VARCHAR2(20) DEFAULT 'ACTIVE',
    created_at DATE DEFAULT SYSDATE,
    CONSTRAINT pk_products PRIMARY KEY(product_id),
    CONSTRAINT uq_product_barcode UNIQUE(barcode),
    CONSTRAINT chk_product_status CHECK(status IN ('ACTIVE','INACTIVE')),
    CONSTRAINT fk_product_category
        FOREIGN KEY(category_id)
        REFERENCES categories(category_id)
);


CREATE TABLE purchases(
    purchase_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    supplier_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    purchase_date DATE DEFAULT SYSDATE,
    invoice_number VARCHAR2(100),
    CONSTRAINT pk_purchases PRIMARY KEY(purchase_id),
    CONSTRAINT fk_purchase_supplier
        FOREIGN KEY(supplier_id)
        REFERENCES suppliers(supplier_id),
    CONSTRAINT fk_purchase_user
        FOREIGN KEY(user_id)
        REFERENCES users_system(user_id)
);



CREATE TABLE purchase_details(
    purchase_detail_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    purchase_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    quantity NUMBER NOT NULL,
    remaining_quantity NUMBER NOT NULL,
    purchase_price NUMBER(10,2) NOT NULL,
    selling_price NUMBER(10,2) NOT NULL,
    expiry_date DATE,
    CONSTRAINT pk_purchase_details
        PRIMARY KEY(purchase_detail_id),
    CONSTRAINT fk_pd_purchase
        FOREIGN KEY(purchase_id)
        REFERENCES purchases(purchase_id),
    CONSTRAINT fk_pd_product
        FOREIGN KEY(product_id)
        REFERENCES products(product_id)
);


CREATE TABLE sales(
    sale_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    customer_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    sale_date DATE DEFAULT SYSDATE,
    total_amount NUMBER(10,2) DEFAULT 0,
    CONSTRAINT pk_sales PRIMARY KEY(sale_id),
    CONSTRAINT fk_sales_customer
        FOREIGN KEY(customer_id)
        REFERENCES customers(customer_id),
    CONSTRAINT fk_sales_user
        FOREIGN KEY(user_id)
        REFERENCES users_system(user_id)
);


CREATE TABLE sale_details(
    sale_detail_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    sale_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    purchase_detail_id NUMBER NOT NULL,
    quantity NUMBER NOT NULL,
    selling_price NUMBER NOT NULL,
    CONSTRAINT pk_sale_details
        PRIMARY KEY(sale_detail_id),
    CONSTRAINT fk_sd_sale
        FOREIGN KEY(sale_id)
        REFERENCES sales(sale_id),
    CONSTRAINT fk_sd_product
        FOREIGN KEY(product_id)
        REFERENCES products(product_id),
    CONSTRAINT fk_sd_purchase_detail
        FOREIGN KEY(purchase_detail_id)
        REFERENCES purchase_details(purchase_detail_id)
);


CREATE TABLE audit_log(
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    action VARCHAR2(100),
    table_name VARCHAR2(100),
    action_date DATE DEFAULT SYSDATE,
    CONSTRAINT pk_audit_log PRIMARY KEY(log_id)
);

DROP TABLE sales CASCADE CONSTRAINTS;


CREATE TABLE warehouses(
    warehouse_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    warehouse_name VARCHAR2(100) NOT NULL,
    address VARCHAR2(200),
    CONSTRAINT pk_warehouse PRIMARY KEY(warehouse_id)
);




